local Lexer = require("src.lexer").Lexer
local TokenType = require("src.token_type").TokenType
local BuiltinClassModule = require("src.builtin_class")

describe("Lexer tests", function()
    local TEST_NEXT_TOKEN = function(text, token_type, class_type)

    end
    before(function()
        TEST_NEXT_TOKEN = function(text, token_type, class_type)
            local lexer = Lexer:new({ text = text })
            local token = lexer:nextToken()
            assert_equal(token.type, token_type)
            assert_equal(token.value.classType, class_type)
        end

        TEST_NEXT_SLOT_PARAM_TOKEN = function(text, token_type, class_type)
            local lexer = Lexer:new({ text = text })
            local token = lexer:nextToken()
            token = lexer:nextToken()
            assert_equal(token.type, token_type)
            assert_equal(token.value.classType, class_type)
        end
    end)

    it("this is a auxiliary", function()
        TEST_NEXT_TOKEN('(', TokenType.LPAREN, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN(')', TokenType.RPAREN, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN(':', TokenType.COLON, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN('-', TokenType.ID, BuiltinClassModule.BUILT_IN_CLASS.BUILT_IN_FUNCTION)
        TEST_NEXT_TOKEN('+', TokenType.ID, BuiltinClassModule.BUILT_IN_CLASS.BUILT_IN_FUNCTION)
        TEST_NEXT_TOKEN('#', TokenType.SHARP, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[]], TokenType.EOF, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[']], TokenType.SINGLE_QUOTE, BuiltinClassModule.BUILT_IN_CLASS.NULL)
    end)

    it("this is a identifier", function()
        TEST_NEXT_TOKEN('*a*', TokenType.ID, BuiltinClassModule.BUILT_IN_CLASS.SYMBOL)
        TEST_NEXT_TOKEN('a', TokenType.ID, BuiltinClassModule.BUILT_IN_CLASS.SYMBOL)
        TEST_NEXT_TOKEN('a-b-c', TokenType.ID, BuiltinClassModule.BUILT_IN_CLASS.SYMBOL)
        TEST_NEXT_TOKEN([["abc"]], TokenType.STRING, BuiltinClassModule.BUILT_IN_CLASS.SIMPLE_BASE_STRING)
        TEST_NEXT_TOKEN([[#\a]], TokenType.CHARACTER, BuiltinClassModule.BUILT_IN_CLASS.CHARACTER)
    end)

    it("this is a keyword", function()
        TEST_NEXT_TOKEN([[defclass]], TokenType.DEFCLASS, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[defconstant]], TokenType.DEFCONSTANT, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[defgeneric]], TokenType.DEFGENERIC, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[defmethod]], TokenType.DEFMETHOD, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[defparameter]], TokenType.DEFPARAMETER, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[defun]], TokenType.DEFUN, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[defvar]], TokenType.DEFVAR, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[do]], TokenType.DO, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[dolist]], TokenType.DOLIST, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[dotimes]], TokenType.DOTIMES, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[if]], TokenType.IF, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[for]], TokenType.FOR, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[in]], TokenType.IN, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[collect]], TokenType.COLLECT, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[map]], TokenType.MAP, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[lambda]], TokenType.LAMBDA, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[let]], TokenType.LET, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[loop]], TokenType.LOOP, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[when]], TokenType.WHEN, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[AND]], TokenType.AND, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[T]], TokenType.T, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_TOKEN([[NIL]], TokenType.NIL, BuiltinClassModule.BUILT_IN_CLASS.NULL)
    end)

    it("this is a slot keyword", function()
        TEST_NEXT_SLOT_PARAM_TOKEN([[:initform]], TokenType.INITFORM, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_SLOT_PARAM_TOKEN([[:initarg]], TokenType.INITARG, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_SLOT_PARAM_TOKEN([[:accessor]], TokenType.ACCESSOR, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_SLOT_PARAM_TOKEN([[:reader]], TokenType.READER, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_SLOT_PARAM_TOKEN([[:writer]], TokenType.WRITER, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_SLOT_PARAM_TOKEN([[:documentation]], TokenType.DOCUMENTATION, BuiltinClassModule.BUILT_IN_CLASS.NULL)
        TEST_NEXT_SLOT_PARAM_TOKEN([[:allocation]], TokenType.ALLOCATION, BuiltinClassModule.BUILT_IN_CLASS.NULL)
    end)

    it("this is a number", function()
        TEST_NEXT_TOKEN('0', TokenType.INTEGER, BuiltinClassModule.BUILT_IN_CLASS.FIX_NUM)
        TEST_NEXT_TOKEN('-0', TokenType.INTEGER, BuiltinClassModule.BUILT_IN_CLASS.FIX_NUM)
        TEST_NEXT_TOKEN('+0', TokenType.INTEGER, BuiltinClassModule.BUILT_IN_CLASS.FIX_NUM)
        TEST_NEXT_TOKEN('0.0', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('0/1', TokenType.INTEGER, BuiltinClassModule.BUILT_IN_CLASS.FIX_NUM)
        TEST_NEXT_TOKEN('-1', TokenType.INTEGER, BuiltinClassModule.BUILT_IN_CLASS.FIX_NUM)
        TEST_NEXT_TOKEN('+1', TokenType.INTEGER, BuiltinClassModule.BUILT_IN_CLASS.FIX_NUM)
        TEST_NEXT_TOKEN('-1.2', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('+1.2', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('+1.2', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('1e+20', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('1e-20', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('+1.2e+20', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('-1.2e-20', TokenType.FLOAT, BuiltinClassModule.BUILT_IN_CLASS.SINGLE_FLOAT)
        TEST_NEXT_TOKEN('1/2', TokenType.RATIONAL, BuiltinClassModule.BUILT_IN_CLASS.RATIONAL)
    end)
end)
