KEYWORDS = {
    DEFCLASS = "defclass",
    DEFCONSTANT = "defconstant",
    DEFGENERIC = "defgeneric",
    DEFMETHOD = "defmethod",
    DEFPARAMETER = "defparameter",
    DEFUN = "defun",
    DEFVAR = "defvar",
    DO = "do",
    DOLIST = "dolist",
    DOTIMES = "dotimes",
    IF = "if",
    LAMBDA = "lambda",
    LET = "let",
    LOOP = "loop",
    WHEN = "when",
    AND = "AND",
    T = "T",
    NIL = "NIL",
}

TokenType = {
    -- non keywords
    LPAREN = '(',
    RPAREN = ')',
    COLON = ':',
    SEMI = ';',
    SLASH = '/',
    SINGLE_QUOTE = '\'',
    DOUBLE_QUOTE = '"',
    SHARP = '#',
    NEGATIVE = '-',
    POSITIVE = '+',
    EXPONENT = 'E',
    ESCAPE = '\\',
    ASTERISK = '*',
    DOT = ".",
    EOF = 'EOF',
    NUMBER = 'NUMBER',
    INTEGER = 'INTEGER',
    FLOAT = 'FLOAT',
    RATIONAL = 'Rational',
    ID = 'ID',
    CHARACTER = 'CHARACTER',
    STRING = 'STRING',

    -- keywords , keyword is kind of ID
    DEFCLASS = "defclass",
    DEFCONSTANT = "defconstant",
    DEFGENERIC = "defgeneric",
    DEFMETHOD = "defmethod",
    DEFPARAMETER = "defparameter",
    DEFUN = "defun",
    DEFVAR = "defvar",
    DO = "do",
    DOLIST = "dolist",
    DOTIMES = "dotimes",
    IF = "if",
    LAMBDA = "lambda",
    LET = "let",
    LOOP = "loop",
    WHEN = "when",
    AND = "AND",
    T = "T",
    NIL = "NIL",
}



return {
    TokenType = TokenType,
    KEYWORDS = KEYWORDS,
}
